In [14]:
import numpy as np 
import pandas as pd

In [15]:
x1 = np.array([2, -1, 1, 3])
x2 = np.array([-1, 1, 0, -2]) 

In [16]:
np.linalg.norm(x1-x2, 1)

np.float64(11.0)

In [17]:
np.linalg.norm(x1-x2, 4)

np.float64(5.185427592735)

In [22]:
D = np.array([[4,4,0],[np.nan, np.nan, 3],[np.nan, 0, 2.5],[1.4,1.2, np.nan],[np.nan, 0, np.nan]]) 

In [23]:
D

array([[4. , 4. , 0. ],
       [nan, nan, 3. ],
       [nan, 0. , 2.5],
       [1.4, 1.2, nan],
       [nan, 0. , nan]])

In [24]:
filled_arr = pd.DataFrame(D).ffill(axis=0).to_numpy()

In [52]:
filled_arr

array([[4. , 4. , 0. ],
       [4. , 4. , 3. ],
       [4. , 0. , 2.5],
       [1.4, 1.2, 2.5],
       [1.4, 0. , 2.5]])

In [53]:
V_D = np.array([[4.3,9.3,7.7],[4.4,1.4,3.4],[11.8,7.7,11.2],[-1.5,10.4,2.3]])

In [54]:
V_D

array([[ 4.3,  9.3,  7.7],
       [ 4.4,  1.4,  3.4],
       [11.8,  7.7, 11.2],
       [-1.5, 10.4,  2.3]])

In [55]:
V_D.mean(axis=0)

array([4.75, 7.2 , 6.15])

In [70]:
np.var(V_D, ddof=1, axis=0)

array([29.69666667, 16.18      , 16.76333333])

In [72]:
sum(np.var(V_D, ddof=1, axis=0))

np.float64(62.64)

In [66]:
VV= (V_D-V_D.mean(axis=0))**2

In [67]:
VV

array([[ 0.2025,  4.41  ,  2.4025],
       [ 0.1225, 33.64  ,  7.5625],
       [49.7025,  0.25  , 25.5025],
       [39.0625, 10.24  , 14.8225]])

In [71]:
VV.sum(axis=0)/(len(VV)-1)

array([29.69666667, 16.18      , 16.76333333])

In [69]:
len(VV)-1

3

angle calculation

In [75]:
np.dot(V_D[2], V_D[3])

np.float64(88.13999999999999)

In [77]:
costheta = np.dot(V_D[2], V_D[3])/(np.linalg.norm(V_D[2],2)*np.linalg.norm(V_D[3],2))

In [83]:
costheta

np.float64(0.4552542080008412)