In [23]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [24]:
dp_df = pd.read_csv('data_points.csv')
dp_df.head()
D = dp_df.to_numpy()

In [25]:
sigma = np.cov(D.T)
print(sigma)

[[ 23.62718475  48.03674304]
 [ 48.03674304 104.15235833]]


In [26]:
np.trace(sigma)


np.float64(127.77954307456855)

In [32]:
Z = D-D.mean(axis=0)
standard_scalar = StandardScaler(with_std=False)
Z_2 = standard_scalar.fit_transform(D)

In [33]:
np.cov(Z_2.T)

array([[ 23.62718475,  48.03674304],
       [ 48.03674304, 104.15235833]])

In [34]:
from sklearn.decomposition import PCA

In [36]:
pca = PCA()
pca.fit_transform(Z_2)
pca.components_

array([[ 0.42286762,  0.90619147],
       [ 0.90619147, -0.42286762]])

In [37]:
pca.explained_variance_ratio_

array([0.99052125, 0.00947875])